Project 3: Loop Perforation
sampsyo/cs6120 pull request #127
Opened 2019-11-14 03:33 UTC by avanhatt

Blog post for proposal #100 

@orichardson @gyauney

2019-12-02 17:28 UTC, sampsyo requested changes
Truly awesome work, y'all! I liked the clear, complete description of the optimization you're pursuing (and its pitfalls). And the probabilistic discussion of error measurement was cool too. Wahoo!

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +1. An external driver program, written in python.
```suggestion
1. An external driver program, written in Python.
```

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +At a high level, `errors` should tell the driver 1) what error metrics we care about for this application, and 2) a float value between 0 and 1 for each metric (0 is perfect, 1 is unacceptable.)
```suggestion
At a high level, `errors` should tell the driver 1) what error metrics we care about for this application, and 2) a float value between 0 and 1 for each metric (0 is perfect, 1 is unacceptable).
```

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +For `sum_to_n1`, let's define a single error metric that's the ratio between our new sum answer and the correct answer:
```suggestion
For `sum_to_n`, let's define a single error metric that's the ratio between our new sum answer and the correct answer:
```

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +Let's walk through what happens now. First, the driver needs a basic sense of what the correct behavior for this application should be, so it builds and executes the application (on the representativ
```suggestion
Let's walk through what happens now. First, the driver needs a basic sense of what the correct behavior for this application should be, so it builds and executes the application (on the representative input, if provided).
```

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +In particular, our implementation does nothing to detect non-determinism, which seems consistent with the prior published work on this topic.
Just for fun: in [ACCEPT](https://dada.cs.washington.edu/research/tr/2015/01/UW-CSE-15-01-01.pdf), we did directly target multithreaded programs and synchronization optimizations, so we measured multiple runs to account for nondeterminism.

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +However, we can see that the error ratio does drastically change as we increase the perforation rate, from perfect for the standard run to completely unacceptable at a perforation rate of 5, as we mi
```suggestion
However, we can see that the error ratio does drastically change as we increase the perforation rate, from perfect for the standard run to completely unacceptable at a perforation rate of 5, as we might expect (skipping 4 in every 5 iterations is skipping every integer except 0!). Note that if our application had multiple loops, we would see a results equal to the number of loops times the number of perforation rates (one run for each).
```

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +However, we can see that the error ratio does drastically change as we increase the perforation rate, from perfect for the standard run to completely unacceptable at a perforation rate of 5, as we mi
Also, "a results."

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +Here, we follow the lead of the original loop perforated paper in making a greedy assumption—that we can choose an final loop perforation strategy based on joining the maximum perforation rate for ea
"loop perforation paper"

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +This strategy makes the very optimistic assumption that errors are not additive; in the published paper their system backtracks in the case that the combined executable is unacceptable.
Hmm, perhaps you mean that "errors _are_ additive"? That is, the error from perforating one loop and the error from perforating another get added together when you perforate them both?

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +- Our driver is less clever about "critically testing" (that is, determining which loops are safe to perforate) than the original paper.
"Criticality" testing?

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +We then use all of these metricscass to compute the Pareto frontier.
```suggestion
We then use all of these metrics to compute the Pareto frontier.
```

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +However the resulting image looks...very bad.
```suggestion
However the resulting image looks... very bad.
```

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +Ultimately, this example illustrates that finding the right error metric might be both difficult and counterintuitive—to get a better image that gained any speedup, we had to select a higher error ra
c.f. "No more sadness about the imperfection of quality metrics."
https://www.cs.cornell.edu/~asampson/blog/closedproblems.html#closed-domains-for-approximation

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +3. `blackscholes`: From the [PARSEC][] benchmark suite. We chose this benchmark for ease and simplicity of compilation, as well as having a straightforward potential for error metrics for the output
If I recall correctly, one of the version of the original loop perforation paper that's out there hilariously perforates the outermost loop in blackscholes—the one that runs the entire identical computation several times! To everyone's shock, you can skip iterations of this loop while losing no accuracy whatsoever.

2019-12-02 17:28 UTC, sampsyo commented on content/blog/2019-11-13-loop-perforation/index.md
> +Each program was run ten times on a 2017 Macbook Pro (2.3 GHz Intel Core i5, 8 GB RAM), and error bars represent 95% confidence intervals.
```suggestion
Each program was run ten times on a 2017 MacBook Pro (2.3 GHz Intel Core i5, 8 GB RAM), and error bars represent 95% confidence intervals.
```

2019-12-05 03:09 UTC, sampsyo approved these changes
Looks great!!

2019-12-05 03:09 UTC, merged

2019-12-10 19:15 UTC, avanhatt commented
fixes #100