Project 3: Strength Reduction for Multiplication
sampsyo/cs6120 pull request #133
Opened 2019-11-15 00:03 UTC by 0x486F626F

2019-12-02 23:21 UTC, sampsyo requested changes
Hi, Hongbo and Wen-Ding—as you have noted in your writeup here, this project is not a complete realization of your idea. I enjoyed reading your discussion and qualitative analysis of the _potential_ of multiplication-to-shift strength reduction, but this project was about LLVM hacking, and there are no results or much description from that. Aside from just counting operations, the appropriate thing to do here would have been to actually _implement_ the strength reduction and measure its performance, as you originally proposed to do in #101.

In any case, I have a few writing suggestions within about the current version of the writeup.

2019-12-02 23:21 UTC, sampsyo commented on content/blog/2019-11-13-multiplication-strength-reduction.md
> +Most modern processors have different latencies and throughputs for different kinds of instructions. It is sometimes possible to find instructions that are mathematically equivalent but fasters in pr
- fasters -> faster
- I'd say that that's true on _most_ processors.
- replace _a_ multiplication … with _a_ bitwise

2019-12-02 23:21 UTC, sampsyo commented on content/blog/2019-11-13-multiplication-strength-reduction.md
> +The strength reduction for multiplication with a constant of powers of $2$ is obvious. However, even the constant is not a power of $2$, reducing multiplications to bitwise shifts is still possible.
even _when_ the constant

2019-12-02 23:21 UTC, sampsyo commented on content/blog/2019-11-13-multiplication-strength-reduction.md
> +$7$ can be also represented as $8-1$, a power of $2$ substracts a constant. In fact, $7$ is "closer" to the next number. If we reduce `x * 7` to `x * (8 - 1) = x * 8 - x * 1 = (x << 3) - x`, it requi
less number -> fewer

2019-12-02 23:21 UTC, sampsyo commented on content/blog/2019-11-13-multiplication-strength-reduction.md
> +3. represent the constant as $2^k-c$, left shift $x$ by $k$ bits, and binary decompose $c$ then substracts those bitwise shifts
subtract

2019-12-02 23:21 UTC, sampsyo commented on content/blog/2019-11-13-multiplication-strength-reduction.md
> +In order to get an estimation of how much cost can be saved by multiplication strength reduction, we have run the cost analysis that reports the average cost reduced of multiplying each integer const
reduced -> reduction

2019-12-02 23:21 UTC, sampsyo commented on content/blog/2019-11-13-multiplication-strength-reduction.md
> +In this analysis, we scaled the cost of add/subtract operations and bitwise operations to $1$ unit. According to [Agner's benchmarks on different AMD processors](https://www.agner.org/optimize/instru
- Agner is the first name, so consider using the full name (Agner Fog).
- _the_ range of the constant factor

2019-12-02 23:21 UTC, sampsyo commented on content/blog/2019-11-13-multiplication-strength-reduction.md
> +In order to show how much cost it can reduce on real benchmark programs, such as PARSEC, we implement an llvm pass to insert two instruction counters: one is to count the cost of the original instruc
Capitalize LLVM.

2019-12-11 22:28 UTC, 0x486F626F commented
> Hi, Hongbo and Wen-Ding—as you have noted in your writeup here, this project is not a complete realization of your idea. I enjoyed reading your discussion and qualitative analysis of the _potential_ of multiplication-to-shift strength reduction, but this project was about LLVM hacking, and there are no results or much description from that. Aside from just counting operations, the appropriate thing to do here would have been to actually _implement_ the strength reduction and measure its performance, as you originally proposed to do in #101.
> 
> In any case, I have a few writing suggestions within about the current version of the writeup.

Sorry, Wen-Ding forgot to add the PARSEC experiment writeup before.
The implementation and experiment of this project did not go as smoothly as we expected, we couldn't do a very thorough experiment as we planed.

2019-12-11 22:38 UTC, sampsyo requested changes
OK, thanks for adding the data! Can I ask you to please add one more notion to your evaluation writeup: what exactly is the “cost” for a given benchmark? Is it, like, “multiplication cost * number of static mul instructions”? Or is there some kind of dynamic measurement going on?

2019-12-21 15:20 UTC, sampsyo approved these changes
OK, thanks for adding that extra information! Now I understand that you used a dynamic instruction count.

2019-12-21 15:21 UTC, merged