Blog post: EDGE and Spatial Path Scheduling
sampsyo/cs6120 pull request #136
Opened 2019-11-16 06:54 UTC by seanlatias

2019-11-16 17:46 UTC, sampsyo requested changes
Looking good so far! Here are some low-level comments, together with some coarse-grained ones:

- There is an old version of your Project 2 report included in this PR.
- To make it clear what's going on with each heuristic, I think examples could really help—especially for your in-class discussion leading.

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +title = "A spatial path scheduling algorithm for EDGE architectures"
Use capital letters (Title Case) for blog post tiles.

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +  [Yi-Hsiang Lai](http://people.ece.cornell.edu/yl2666/) is a 4th-year Ph.D. student interested in computer architecture, high-level synthesis, and programming language.
languages (plural)

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +To achieve all four features mentioned in the previous section, the TRIPS architecture builds up an array of execution units, where the instructions can be executed, and the computation results can b
Maybe link to TRIPS the first time you mention it (instead of the title below)?

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +With the rising complexity of existing applications and the need for low-power solutions for emerging silicon technology, we need an instruction-set architecture (ISA) that provides the following fea
In this overview, it might be useful to break down the context so people know what this post will mostly be about. In particular, you can say that it's about compilation techniques for a different kind of ISA than the standard ones we've studied for most of the semester. Then you can launch into this background about why EDGE itself is important. But this motivation really belongs in the section that motivates/introduces EDGE, rather than the overview, which should be about the compiler techniques.

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +To achieve all four features mentioned in the previous section, the TRIPS architecture builds up an array of execution units, where the instructions can be executed, and the computation results can b
To help the reader understand why this creates an interesting compilation problem, it might be useful to use an example showing how an instruction specifies where inputs come from and results go to—in contrast to the register operands common in ordinary von Neumann ISAs.

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +A naive way to compile a program and deploy it to a TRIPS architecture is to generate the RISC assembly first. Then, the compiler analyzes the data dependence and builds a dataflow graph (DFG). The c
"all possible executions" is a little unclear—maybe this could use a little more explanation? Is the set of all "executions" infinite for a `while` loop?

Also, this paragraph talks about RISC assembly, but RISC ISAs typically don't have `if`/`for` constructs.

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +One observation from the compilation flow is that the out-of-order execution is enabled naturally with the TRIPS architecture. Namely, the execution order is determined dynamically at runtime. The co
"at run time" https://capra.cs.cornell.edu/styleguide/#runtime

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +There is no doubt that there exist many optimization possibilities within this naive compilation flow. For instance, how should we group the instructions into blocks? How to perform branch prediction
Consider giving the title of the paper when you link to it.

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +The main idea of both the baseline and the SPS algorithms are the same. First, we create an initial set contains certain instructions. Then for each instruction in the set, we assign it with a **plac
"is how to determine the cost" -> "determines the cost"

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +The initial set contains the instructions having no or scheduled inputs. For GRST, it adopts several heuristics. For example, it schedules the instructions within the critical paths first. It also co
"no or scheduled inputs" sounds a little weird—do you mean "no unscheduled inputs"?

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +One naive way to evaluate the scheduling results is by comparing them with the optimal results. However, it is an NP-complete problem. To solve that, the authors use simulated annealing, which can fi
approximate optimal *solution*

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +The main idea of this algorithm is that, for each instruction, it calculates the cost for each possible position in the ALU array. Then the final placement cost is the minimal cost among all position
at least one scheduled input (singular)

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +To calculate the final penalty, the algorithm sums up both intra- and intro-contention for ALUs. In addition, it introduces two factors, which are fullness and criticality, respectively. For the form
how full a block *is*?

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +The main idea of this heuristic is performing loop-related optimizations. The algorithm performs the following three heuristics. First, smaller loops (in terms of the number of blocks) will be schedu
I'm a little confused by the "first" and "second" terminology here—maybe use "earlier" or something if you don't literally mean "first"?

2019-11-16 17:46 UTC, sampsyo commented on content/blog/2019-11-18-edge-architecture.md
> +The authors selected a wide range of benchmarks with different levels of concurrency and memory behavior. Since dense blocks require more algorithmic work, the authors modified the selected benchmark
It would be useful to break down a little bit more about those "step by step" results, showing which parts of the heuristics mattered more.

2019-11-17 01:26 UTC, seanlatias commented on content/blog/2019-11-18-edge-architecture.md
> +To achieve all four features mentioned in the previous section, the TRIPS architecture builds up an array of execution units, where the instructions can be executed, and the computation results can b
I do not quite understand this comment.

2019-11-17 01:31 UTC, seanlatias commented on content/blog/2019-11-18-edge-architecture.md
> +To achieve all four features mentioned in the previous section, the TRIPS architecture builds up an array of execution units, where the instructions can be executed, and the computation results can b
Never mind. I'll rearrange the overview and you can see if it makes more sense.

2019-11-17 07:42 UTC, sampsyo commented
Looks great overall! The PR is still showing an unrelated file being modified, for some reason… but other than that, I think this is ready.

2019-11-17 14:00 UTC, seanlatias commented
I removed the other file.

2019-11-17 17:11 UTC, sampsyo approved these changes
Looks great; thanks!

2019-11-17 17:11 UTC, merged