Rachit final blog post
sampsyo/cs6120 pull request #212
Opened 2020-09-11 21:02 UTC by rachitnigam

WIP

2020-09-22 12:09 UTC, sampsyo requested changes
Looks great! Just some grousing about commas within. :smileY:

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +and generation problems.
FWIW, I think neither of the last two commas are necessary.

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +middle of the high-level input programs that imply an abstract architecture,
Also an unnecessary comma (because the RHS is a dependent clause).

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +FuTIL programs.
Maybe add commas after "lowering" and "code generation" to match the one after "type checking."

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +currently does not support signed, fixed-point, or floating arithmetic. It
```suggestion
currently does not support signed, fixed-point, or floating-point arithmetic. It
```

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +Following an example FSM definition:
Needs a verb?

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +In the next section, we analyze designs generates from the FSM language and
```suggestion
In the next section, we analyze designs generated from the FSM language and
```

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +preserving their functionality.
Very interesting question! Perhaps @sgpthomas would be interested as well.

2020-09-22 12:09 UTC, sampsyo commented on content/blog/2020-09-11-futil-vs-fsm/index.md
> +high-level language and simplify the design iteration process even more.
"high-level languages" plural, perhaps?

2020-09-28 19:27 UTC, rachitnigam commented
Comments resolved!

2020-09-29 11:18 UTC, sampsyo approved these changes
Excellent!! Congratulations on finishing. :smiley:

2020-09-29 11:19 UTC, merged