Blog post for Unified Theory of Garbage Collection (11/04)
sampsyo/cs6120 pull request #219
Opened 2020-10-28 18:23 UTC by mdmoeller

Merging my blog post for Wed. of next week!

2020-11-02 00:50 UTC, sampsyo requested changes
Awesome work! I thought the list of brief summaries of the different intermediate design points was very clear and a good way to structure the post.

I have just a couple of nitpicky suggestions within.

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +in the simplest approach one must pause execution to 'trace' all live objects
I'd probably use double quotes at the "top level" of nesting.

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +Believe It's Not Butter have the same deep structure.
😂

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +  but do reference counting on the mature remaining space of the heap.
Neither here nor there, but: this always struck me as a pretty sweet design point if you can make it work.

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +* **Train Algorithm.** (Presented but not analyzed). While this approach was
```suggestion
* **Train Algorithm.** (Presented but not analyzed.) While this approach was
```

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +  implementing.
Maybe this bullet could use one more sentence about what the approach actually is before adding this additional commentary?

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +  but with some tracing of certain "candidates" mixed in to detect cycles (i.e.
```suggestion
  but with some tracing of certain "candidates" mixed in to detect cycles (i.e.,
```
https://capra.cs.cornell.edu/styleguide/#egie

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +for a particular system (and I guess also the constancy of those constants?).
Hmm, not entirely sure what you mean by this parenthetical—are you suggesting that it's not entirely certain that these factors are actually constants in all settings? That would be reasonable!

2020-11-02 00:50 UTC, sampsyo commented on content/blog/2020-11-04-unified-theory-gc/index.md
> +validate any decisions against benchmark performance anyway.
Great question; I don't know either! I can see it perhaps being useful as a first step, in combination with validation on real benchmarks.

2020-11-03 19:10 UTC, mdmoeller commented
Incorporated all suggested changes into 17a0b7b.

2020-11-04 02:22 UTC, sampsyo approved these changes
Excellent.

2020-11-04 02:22 UTC, merged