Final Project Blog: Loop Unrolling in Petr4
sampsyo/cs6120 pull request #247
Opened 2020-12-19 04:06 UTC by stp59

closes #228

2020-12-19 23:05 UTC, sampsyo requested changes
Great! This is a cool outcome, and I'm glad you were able to make it work within the real Petr4 codebase. :tada: I have a few suggestions within—most notably about including some P4 code examples to illustrate what a loop looks like in the parsers you're processing.

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +However, loops in the domain of network programming languages have entirely unique significance. Typical hardware targets (e.g. routers) are quite different from traditional CPUs, sometimes requiring
Always use a comma after "e.g." https://capra.cs.cornell.edu/styleguide/#egie

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +This project explores this unique treatment of loop unrolling in the network programming language P4. P4 is used to program network switches and routers, and is of the most practical and widely used
Stray "of" in "is of the most practical"?

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +Unfortunately, P4's only [specification](https://p4.org/p4-spec/docs/P4-16-v1.2.0.html) comes in the form of a ~200 page pdf document consisting of vague English descriptions, pseudocode, and example
Capitalize "PDF."

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +```
Use a Markdown blockquote instead of a code block. https://commonmark.org/help/tutorial/05-blockquotes.html

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +It is almost unbelievable that the above two blocks comprise the entirety of the P4 spec's treatment of this problem, especially in a turing complete language which targets hardware that is often not
In the programming language English, "blocks" are called "paragraphs." 😃

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +It is almost unbelievable that the above two blocks comprise the entirety of the P4 spec's treatment of this problem, especially in a turing complete language which targets hardware that is often not
Capitalize "Turing."

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +Petr4 is a long-term project which strives to build a formally verified end-to-end compiler for P4, along with [formal operational semantcs](https://popl21.sigplan.org/details/POPL-2021-research-pape
Since this is the first mention of Petr4, make the term itself a link.

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +However, the common case is to use a natural loop in the parser to populate various data structures provided by the language. In particular, parser loops that extract from the packet on each iteratio
A code example could _really_ help here to illustrate what these "natural loops" look like. Is there a short one you can include?

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +2) Every distinct natural loop should include a block which both extracts from the packet and dominates all paths to the loop header
I'm not sure what it means to "dominate" a path. We usually say that CFG nodes dominate other CFG nodes. Maybe you mean "dominates the loop header"?

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +My implementation runs these checks, providing the user with the options to fail when they are not satisfied or merely to emit a warning and produce unmodified code. Surprisingly, this turned out to
Again, examples might be nice here, especially of programs that your checker would warn/error on.

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +For correctness, I begin with a minimal collection of toy p4 programs which I developed for the sake of test-driven development of loop unrolling. Residing in `petr4/unroll-test`, these are edge-case
Link to the directory of tests on GitHub?

2020-12-19 23:05 UTC, sampsyo commented on content/blog/2020-12-18-stp59-final.md
> +For correctness, I begin with a minimal collection of toy p4 programs which I developed for the sake of test-driven development of loop unrolling. Residing in `petr4/unroll-test`, these are edge-case
I again think that including some small code examples here could really help illustrate what's going on.

2020-12-24 23:11 UTC, stp59 commented
I believe I have addressed all of your suggested changes!

2021-01-01 17:04 UTC, sampsyo approved these changes
Looks good; thanks!!

2021-01-01 17:04 UTC, merged