Shrimp: Symbolic Verification for Bril
sampsyo/cs6120 pull request #29
Opened 2019-09-24 18:30 UTC by rachitnigam

2019-09-26 04:01 UTC, rachitnigam commented
@sampsyo looks like the `extra.bio` field is ignored if placed after authors and errors in zola if placed before the authors.

2019-09-26 14:58 UTC, sampsyo commented
It needs to go before, or you can use `[extra]` to put it afterward. (See the TOML docs.) I might be able to help if you include an error message.

2019-09-27 17:06 UTC, sampsyo requested changes
Looks awesome! Here are a few writing suggestions (and one CSS thing).

2019-09-27 17:06 UTC, sampsyo commented on content/blog/2019-09-25-a-verification-backend.md
> +bad decision to give each Bril instruction it's own structure that is a sub-type of a `dest-instr` structure
```suggestion
bad decision to give each Bril instruction its own structure that is a sub-type of a `dest-instr` structure
```

2019-09-27 17:06 UTC, sampsyo commented on content/blog/2019-09-25-a-verification-backend.md
> +bad decision to give each Bril instruction it's own structure that is a sub-type of a `dest-instr` structure
Is `dest-instr` a thing of your own invention? Could use a little intro: "we made a type called `dest-instr` that…"

2019-09-27 17:06 UTC, sampsyo commented on content/blog/2019-09-25-a-verification-backend.md
> +we were only comparing that fields in `dest-instr` where the same. We forgot to compare the actual
```suggestion
we were only comparing that fields in `dest-instr` were the same. We forgot to compare the actual
```

2019-09-27 17:06 UTC, sampsyo commented on content/blog/2019-09-25-a-verification-backend.md
> +This made it easy to find and fix a rather embarrassing bug in the LVN implementation.
🎉🎉🎉

2019-09-27 17:06 UTC, sampsyo commented on content/blog/2019-09-25-a-verification-backend.md
> +[memory models](), and [operating systems]() code using symbolic verification
Looks like these links need to be filled in?

2019-09-27 17:06 UTC, sampsyo commented on content/blog/2019-09-25-a-verification-backend.md
> +but require several person-years of work to implement, specify[^1],
Footnote marker goes after the comma.

2019-09-27 17:06 UTC, sampsyo commented on content/blog/2019-09-25-a-verification-backend.md
> +[^1]: The problem of specifying the correctness condition of a compiler is itself
Looks like the site's CSS needs a tweak to make footnotes display correctly?

2019-10-02 14:53 UTC, sgpthomas commented on content/blog/2019-09-25-a-verification-backend.md
> +It lets us write normal Racket programs and does the work of automatically lifting them
done

2019-10-02 14:54 UTC, sgpthomas commented on content/blog/2019-09-25-a-verification-backend.md
> +Rosette will convert this into an SMT formula and verify it's correctness using
done

2019-10-02 14:57 UTC, sgpthomas commented on content/blog/2019-09-25-a-verification-backend.md
> +interpretation would produce the formula `x + 5`.
done

2019-10-02 15:00 UTC, sgpthomas commented on content/blog/2019-09-25-a-verification-backend.md
> +and does something like: `x + 2 + 3 => 1 + 2 + 3 => 6`. A symbolic interpreter works on the same types of programs,
done

2019-10-02 15:04 UTC, sgpthomas commented on content/blog/2019-09-25-a-verification-backend.md
> +SMT theories are undecidable in general and even when you restrict it to
done

2019-10-02 15:04 UTC, sgpthomas commented on content/blog/2019-09-25-a-verification-backend.md
> +paths in a program increases exponentially with the size of the program,
done

2019-10-02 15:11 UTC, sgpthomas commented on content/blog/2019-09-25-a-verification-backend.md
> +unnoticed.
done

2019-10-02 16:08 UTC, sgpthomas commented
@sampsyo We have addressed the changes and are ready to merge.

2019-10-02 16:42 UTC, sampsyo approved these changes
Awesome; nice work!

2019-10-02 16:43 UTC, merged