Blog post for Numpy Peephole Improvements with JAX
sampsyo/cs6120 pull request #338
Opened 2022-05-20 04:07 UTC by atucker

closes #331

Thanks for a great semester! I really enjoyed the class!

2022-05-24 22:41 UTC, sampsyo requested changes
Nice! This project seems very cool and perhaps very useful! Have you considered trying to get the word out—maybe it's just a matter of tweeting this blog post once it's public or something?

One suggestion you'll see inline is that I found myself wishing for more details about what the tool actually consists of. You gave us a good high-level framing, but it jumps pretty quickly to the evaluation without describing what the implementation looked like. Just a bit of detail there could help a lot.

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +The basic design of the project is to convert code which uses numpy into an intermediate representation, perform the peephole optimizations on the intermediate representation, and then execute the co
I'd probably spell it NumPy, and maybe link to [its homepage](https://numpy.org).

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +title = "Peephole Improvements for Numpy with JAX"
Numpy -> NumPy, probably

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +Thankfully, there is already a project which converts numpy code into an intermediate representation, then then executes it. [JAX](https://jax.readthedocs.io/en/latest/) is a project which combines a
python -> Python

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +Jaxpr is JAX's intermediate representation for numpy code. While obviously different from BRIL, I found it to be pretty similar and pretty simple, so I was happy to build on top of Jaxpr rather than
BRIL -> Bril

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +The most useful thing that I learned from trying to read the JIT code was that JAX's JIT compilation is based on tracing all of the uses of jax's version of numpy, and then rerunning code based on th
Is it JAX or jax (both are used in this sentence)?

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +To be more explicit, when you JIT compile code using JAX it waits until the first time the function gets used, then it traces everything that function does, then it builds a Jaxpr representation base
Add backticks around `if`?

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +3. The logsumexp peephole improvement [actually fixes](https://github.com/atucker/jax-peephole/blob/main/tests/peephole_fixes_logsumexp_overflow.out) an overflow issue! 🎉🎉🎉
Cool!

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +## Hardest parts
Before jumping into the hardest parts, what do you think about an "Implementation" section to tell us more about exactly what you did? Presumably it's some kind of a pass? How does it recognize the pattern it's looking for? How flexible were you able to make the pattern-matching? That sort of thing.

2022-05-24 22:41 UTC, sampsyo commented on content/blog/2022-05-19-numpy-peephole-improvements-with-jax.md
> +While it might be tricky to do this as a peephole improvement because JAX doesn't have side-effectful code like printing, it might be a reasonable amount of effor to simply write a Jaxpr interpreter
Cool idea! Reminds me a lot of [Herbgrind](http://herbgrind.ucsd.edu):

> Herbgrind is a dynamic, binary, program analysis to find the root cause of floating point error in large programs.

2023-03-01 17:32 UTC, sampsyo commented
Hi! I know it's been a while, but would you be interested in wrapping this up so we can publish it?

2023-03-09 11:55 UTC, atucker commented
Hey, thanks for reaching out! Sorry I didn't get to this earlier -- I was in Germany then doing my A exam, but I'd be happy to wrap this up.

2023-08-14 17:48 UTC, sampsyo commented
Hello! I am closing old issues from last year's offering to prepare for the next iteration of the course. If you would like to have this blog post published, please just leave a note and we can reopen the thread.

2023-08-14 17:48 UTC, closed without merging