[Blog - Final Project] Allo Frontend Integration for AMC
sampsyo/cs6120 pull request #422
Opened 2023-12-11 03:40 UTC by matth2k

This is the blog post for the final project by @yxd97 and I.

2023-12-11 18:51 UTC, matth2k commented
Fixes #400

2023-12-17 17:54 UTC, sampsyo requested changes
Hey, Matt and Yixiao—really nice work on the writeup here! I found it very clear and direct. And nice work on the broader AMC project more broadly, of course. :smiley: I have just a couple of minor suggestions where you could add a tiny bit more detail!

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +High-Level Synthesis (HLS) is one such solution to solve the problem of hardware design productivity. The general idea is to raise the level of abstraction from the commonly-used register transfer le
Missing comma after the first occurrence of `e.g.`. :smiley:

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +The [CIRCT](https://circt.llvm.org/) project expands the MLIR-based development methodology for hardware design. It represents key components of hardware as MLIR dialects such as finite state machine
Perhaps reword "pathway to finally to synthesizable Verilog"?

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +    s = customize(kernel)
Maybe it would be useful to describe what `customize` does?

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +    hcl_out = f(A, B)
To clarify, is this RTL simulation or some kind of AMC-specific interpretation?

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +        return matmul(A, B)
Do you think you could add something quick here about how the Python frontend works (and exactly which component is responsible for it)? Namely, I think the answers are:

* It works by statically inspecting the Python AST and directly translating a subset of that to the `affine` dialect. (That is, it does _not_ work with the dynamic operator-overloading approach that some other Python frontends do.)
* The component that does this Python AST translation is either part of HCL itself… or perhaps it is from something external like the [npcomp](https://github.com/google/mlir-npcomp/tree/archived) project?

Understanding exactly who/what does this translation and how it works will help the reader see what the power and limitations are here.

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +The top row of dependencies are C++ codebases linked together as static libraries. We enter this library with input MLIR generated from HCL. On the backend, we emit Calyx which is lowered to Verilog
Just noting here that, while this overview is helpful, it doesn't directly answer the question I have above about the first step of the translation from Python. No need to change this here if you explain that step somewhere above.

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +```
What do you think about adding a quick description (doesn't need to be exhaustive) of the various MLIR constructs (ops & types) that are shown here? Namely, the reader might be able to understand this example a bit better if they got a very brief description of what `amc.memory` and `amc.dynamic_port` are doing in the "signature" here, and how `amc.alloc`, `amc.create_port`, and `amc.extern` can be combined to implement it.

2023-12-17 17:54 UTC, sampsyo commented on content/blog/2023-12-09-hcl-amc/index.md
> +The role of the AMC compiler is to take in a high-level description of memory organization (as seen above) and figure out how to best compile it to the target architecture. It accounts for some of th
Could you perhaps explain a tiny bit more about what "the context in which the memory is being used" means? Is it the HCL-dialect code that consumes this `amc.memory`?

2023-12-17 18:13 UTC, matth2k commented
@sampsyo Thanks for pointing out all the spots that need clarification. It's very helpful feedback. I'll address all these points eventually and update the PR.

2023-12-20 19:13 UTC, matth2k commented
I think I addressed all of the comments. Feel free to let me know if it needs any more refinement.

2023-12-23 00:33 UTC, sampsyo approved these changes
Awesome; this looks really great! Nice work!!

2023-12-23 00:33 UTC, merged