[Blog] AsyncBril
sampsyo/cs6120 pull request #424
Opened 2023-12-11 19:20 UTC by evanmwilliams

Final project for CS 6120 with @emwangs and @he-andy

2023-12-11 23:55 UTC, evanmwilliams commented
Here's the link to our actual code: https://github.com/sampsyo/bril/pull/305

https://github.com/he-andy/bril

2023-12-17 20:12 UTC, sampsyo requested changes
This is a really interesting idea! I like how it resulted in a design with a separate heap for explicitly allocated atomics. I think it would be even more awesome if you had gotten some actual parallel computations going for the benchmarking effort, but the implementation itself is pretty cool.

I have one major IL design suggestion inline. I'd be interested in your thoughts on this alternative.

I also note that you changed your project entirely from the original proposal in #394. Can you say anything about why and how you decided to scrap your original idea?

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +By Andy He, Emily Wang, and Evan Williams
Your names display at the top of the post when rendered, so no need to duplicate them here.

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +by Boehm: threads cannot be implemented as a library.
Maybe it would be nice to make this a link to the paper?

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +primitive types (i.e. `atomicint`). Promises are a fundamental
I'd recommend always using a comma after "e.g." and "i.e.". https://capra.cs.cornell.edu/styleguide/#egie

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +in `state.heap.memory` when `alloc` is called simultaneously between threads.
I think it makes sense to assume an audience that knows about Bril but not about the Rust implementation… so your reader probably doesn't know what `state.heap.memory` is. Maybe use a direct description of what this is (e.g., the interpreter data structures that implement the heap)?

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +`Resolve`, significantly enhancing its capabilities in threaded execution and
```suggestion
`resolve`, significantly enhancing its capabilities in threaded execution and
```

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +  prom2: promise<bool> = call @mod2 size2;
There's no need to do anything particular about this now, but here is a broader comment on the language design here. Unlike many async/await frameworks, you've elected to avoid any changes to function definitions and the `call` instruction; instead, the `call` instruction is "overloaded" to do two things: (1) call a function normally, and (2) spawn a new thread.

While this minimizes the surface area of the changes, it does create a bit of awkwardness in the final language. The big one I can see is that it's not possible to create or call "normal" functions that happen to manipulate promises. For example, the identity function on integer promises cannot be used:

```
@id(p: promise<int>): promise<int> {
  ret p;
}
```

In other words, because the way you define async functions is with their return type, it's not possible to write non-async functions that happen to use the `promise<T>` type in call cases.

---

Thinking about it a little bit, one possible alternative here would be to put all the async-ification into the call instruction. That is, in this alternative version, functions need not mark themselves as returning `promise<T>` in order to be called from a spawn. Instead, we introduce a special `spawn` instruction that works like `call`. Something like this:

```
@something(x: int): int {  // just a normal function!!
  y: int = add x x;
  ret y;
}

@main() {
  five: int = const 5;
  i: int = call @something five;  // normal call
  p: promise<int> = spawn @something five;  // async call
}
```

That is, the same function `@something` could be used in either kind of call (synchronous or asynchronous); we just distinguish based on the invocation rather than the definition.

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +We have introduced two critical syntax features to Bril: `Promise<T>` and
```suggestion
We have introduced two critical syntax features to Bril: `promise<T>` and 
```

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +`Resolve` mechanism. In the `@main` function, two promises are created: `prom`
As above, I think you want to globally make `Promise` and `Resolve` lower-case to match the syntax…

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +promise was left unresolved. In general, all promises should be resolved.
Maybe it would be good to take a stance here and say "it is an error to leave a promise unresolved"? As it stands, I can't tell whether it's actually disallowed or just discouraged.

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +and experimenting with compiler design and parallel computing concepts.
Maybe you could point out the exact parts of the rust stdlib that you used for these atomics? Do you literally mean the elementary types from `std::sync::atomic`? Maybe you could discuss why you chose this over `std::sync::Mutex`?

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +Here's an example of how atomics work in Bril:
Do you think you could include a direct listing of all the new operations you added? Just a simple bulleted list could help complement the in-context use in the example.

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +variable while simultaneously retrieving its old value. Another `loadatomic`
I'm not sure what you mean by "particularly useful" here… this seems like the _only_ thing it is useful for?

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +thread-safe and prevent race conditions in concurrent environments.
Really cool! I like your suite of atomic operations, and I like this demo of how to use them to build up to a more usable synchronization construct.

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +together. Below, we show the execution time in miliseconds against the number
I think I would delete the sentence about the matrix multiply… I don't think your microbenchmark/stress-test has much in common with a GEMM. :smiley: It's fine for it just to be itself, i.e., a contrived microbenchmark does nothing more than seeing how fast you can issue atomics.

2023-12-17 20:12 UTC, sampsyo commented on content/blog/2023-12-11-AsyncBril.md
> +improvements. This makes sense, as we are taking direct advantage of
One thing I don't quite understand about this benchmark: how does it change as you scale up the number of threads? Is the amount of work (total increments) held constant, so when you have N threads you are incrementing the counter, like, 2000000/N times?

2023-12-17 22:45 UTC, he-andy commented on content/blog/2023-12-11-AsyncBril.md
> +  prom2: promise<bool> = call @mod2 size2;
I think originally what I had in mind was that we could use a this as a drop in replacement for functions already implemented, so if we had a function f: int -> int, we could wrap it in a function f_promise: int -> promise<int>. But I think your idea where we could have a dedicated async call function would've definitely been a cleaner approach to satisfy what I had in mind (and simpler to implement too, I think). Thank you for the suggestion!

2023-12-18 19:04 UTC, evanmwilliams commented
@sampsyo For sure, there were two main reasons we pivoted from the original idea.

The first is that we weren't confident in our ability to implement re-looper with the time we had for the project. We read the paper and it was pretty gnarly to understand, and without re-looper the translations become pretty trivial so maybe the scope of the project wasn't well suited for us.

The other reason is that we were much more interested in concurrency (especially after the last lecture). We wanted to do something related to performance and lost interest in our original idea. We thought the Async idea was a cool idea way to explore this. We probably should've let you know before we pivoted - in all honesty we switched up pretty late and were heads down on development so it slipped our minds - sorry about that!

2023-12-18 22:09 UTC, sampsyo commented
Cool; thanks for the extra detail!

2025-06-05 15:45 UTC, sampsyo commented
Hi, Evan et al.! This PR has "timed out"—please let me know if you'd like to reopen it.

2025-06-05 15:45 UTC, closed without merging