[Blog Post] Add blog post for BTOR2 interpreter final project
sampsyo/cs6120 pull request #426
Opened 2023-12-11 20:06 UTC by obhalerao

Add blog post to finish up the BTOR2 interpreter final project.

[Link to repo](https://github.com/NgaiJustin/btor2i)

Closes #397.

2023-12-17 20:53 UTC, sampsyo requested changes
Really nice work, y'all! I'm delighted with the outcome here; the end-to-end testing is the most important part, and it's cool that you were able to tack on a substantial optimization while preserving correctness. Nice work!!!

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +[Link to project repository](https://github.com/NgaiJustin/btor2i)
What do you think about working this in more elegantly below? You could link the first time you mention that you have implemented an interpreter, for example. :smiley:

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +btor2 is a model checking language designed for hardware; it provides this functionality at a word level, and also includes functionality for persistent state. Words of arbitrary length can be repres
Maybe some kind of a link to explain btor2 (to the btor2tools repo, or the relevant paper) would be helpful?

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +The creators of btor2 included three key tools: a parser, a random state simulator, and a witness checker, all written in C. Notably missing from this list is an interpreter for the language; though
This paragraph could go one step farther to crystallize what is currently missing: a way to _specify the inputs_ to a btor2 program (to run it and observe the outputs). None of the other modes let you tell it the input you want to use to run the program. Witnesses sorta do, but you also have to specify the output, which isn't very useful. :smiley:

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +We first sketched out a basic design of the structure of our project. We found a library called btor2tools-sys that provides Rust bindings for the btor2 parser that the creators released, so we chose
Please link to btor2tools-sys.

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +The structure of btor2 instructions is relatively simple; it’s similar to bril in that there are no nested instructions, and it’s even simpler in that there is no control flow: all instructions are e
bril -> Bril

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +We first wrote a representation of bit vectors in Rust. It turns out that Rust already has a builtin BitVec crate, but as the bit vectors in btor2 require more functionality than the standard Rust cr
Please link to `BitVec`. I actually don't think it's built-in—it's just a popular third-party library.

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +We then wrote a more optimized version of our interpreter, aiming to improve the memory locality. Instead of allocating new memory for every bit vector and storing them in a vector, we instead comput
This is a nice description of a straightforward optimization!!

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +We chose not to implement the overflow opcodes, as we felt as though they were not very interesting to do and would not be very applicable in our tests.
Can you briefly explain what the overflow opcodes do?

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +The primary difficulty we dealt with while working on this project was ensuring that the libraries we were using were correct and up-to-date. Because this language is not yet very widely used, the to
Wow; that's quite a limitation in the parser!! It does motivate me to suggest that, in the future, we replace the existing C parser with a handcrafted Rust one…

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +We wrote two main types of end-to-end tests to ensure correctness for this assignment: many small core tests that tested each major opcode we supported for combinational logic (we did not manage to c
Please link to Calyx and/or Cider.

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +We wrote two main types of end-to-end tests to ensure correctness for this assignment: many small core tests that tested each major opcode we supported for combinational logic (we did not manage to c
Please make your use of "btor2" vs. "BTOR" consistent.

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +| Faster intepreter | 2.1 ± 1.2 ms | 3.7 ± 0.9 ms  | 42.1 ± 4.0 ms | 388.7 ± 18.0 ms | 4073.9 ± 280.2 ms  | 27950.3 ± 1032.5 ms |
Nice! It's really cool that your optimized heap turned out to be such a substantial win.

2023-12-17 20:53 UTC, sampsyo commented on content/blog/2023-12-11-btor2i.md
> +For more detailed results, including runtimes for each of the individual benchmarks, feel free to check out our project repository.
This would be another good place to link to your code.

2023-12-18 18:11 UTC, obhalerao commented
Thank you for your comments, Prof. Sampson! We really enjoyed working on this as well and taking 6120 as a whole :)

2023-12-18 22:10 UTC, merged