closes #27
sampsyo/cs6120 pull request #49
Opened 2019-09-26 09:29 UTC by epeguero

2019-10-02 21:02 UTC, sampsyo requested changes
This is awesome! I really like the ruminations on the spiritual path of a syntax highlighter. Here are just a few low-level writing suggestions.

2019-10-02 21:02 UTC, sampsyo commented on content/blog/2019-09-25-vim-syntax-highlighting.md
> +We can solve this by *escaping each 'escaping' backslash with a backslash, except for those backslashes that escape backlashes.* (it's no wonder the leading Vimscript tutorial recommends [beer](http:
```suggestion
We can solve this by *escaping each 'escaping' backslash with a backslash, except for those backslashes that escape backlashes.* (It's no wonder the leading Vimscript tutorial recommends [beer](http://learnvimscriptthehardway.stevelosh.com/chapters/08.html) to accompany some of the exercises.)
```

2019-10-02 21:02 UTC, sampsyo commented on content/blog/2019-09-25-vim-syntax-highlighting.md
> +We can solve this by *escaping each 'escaping' backslash with a backslash, except for those backslashes that escape backlashes.* (it's no wonder the leading Vimscript tutorial recommends [beer](http:
:beers:

2019-10-02 21:02 UTC, sampsyo commented on content/blog/2019-09-25-vim-syntax-highlighting.md
> +As I've described it, a syntax highlighters principle job is to give a meaningful visual presentation to an evolving syntax tree.
```suggestion
As I've described it, a syntax highlighter's principal job is to give a meaningful visual presentation to an evolving syntax tree.
```

2019-10-02 21:02 UTC, sampsyo commented on content/blog/2019-09-25-vim-syntax-highlighting.md
> +- Syntactically-aware code editing and navigation, such as automatic indentation, folding, variable renaming, etc...
```suggestion
- Syntactically-aware code editing and navigation, such as automatic indentation, folding, variable renaming, etc.
```

I think "etc." is fine by itself; it doesn't need to be doubled up with an ellipsis.

2019-10-02 21:02 UTC, sampsyo commented on content/blog/2019-09-25-vim-syntax-highlighting.md
> +- etc..
```suggestion
- etc.
```

2019-10-09 23:00 UTC, epeguero reviewed
Thanks for the edits.
I made a change to that grammatically weird sentence, clarified what I meant a bit.
Let me know if there are issues with my commits; I'm learning how to resolve a pull request review as I go.

2019-10-12 14:18 UTC, merged

2019-10-12 14:19 UTC, sampsyo commented
Nice work! This looks great. Merged & published!