Blog Post: POSH a TLS Compiler that Exploits Program Structure
sampsyo/cs6120 pull request #80
Opened 2019-10-21 00:23 UTC by dz333

2019-10-21 21:30 UTC, sampsyo requested changes
Very nice, Drew and Josh! This is great. I just have a few suggestions (mostly proofreading) within.

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +is a software-level technique that utilizes those features),
```suggestion
is a software-level technique that utilizes those features)
```

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +will not rollback cache state; this implies that squashed tasks can
```suggestion
will not roll back cache state; this implies that squashed tasks can
```

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +to heuristics.
Maybe briefly state what an "optimal" task decomposition would look like? (That is, state the criterion for optimality.) This will help the reader believe that finding such an optimum would be NP-hard.

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +Its primarily heuristic leverages the existing high level program structure;
```suggestion
Its primary heuristic leverages the existing high level program structure;
```

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +```
You can use a Markdown block quote for such things:

```md
> All these programmer-generated structures are taken
> as hints to delineate code sections with a relatively independent and
> sizable amount of work.
```

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +using some configuration of the compiler, and look at statistics (e.g. execution time or memory behavior).
```suggestion
using some configuration of the compiler, and look at statistics (e.g., execution time or memory behavior).
```

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +or [`store-conditional`](https://en.wikipedia.org/wiki/Load-link/store-conditional).
Not sure you actually want these in Markdown code backticks? They don't really seem like code.

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +and performant synchronization primitive.
Makes me wonder whether someone should try implementing a SOTA TLS system on TSX. The limiting factor is the L1 size and associativity, of course, but maybe you could get _some_ benefit…

2019-10-21 21:30 UTC, sampsyo commented on content/blog/2019-10-23-posh/index.md
> +will be squashed whenever real(x) != pred(x).*
Replace "is" with "be" (twice) for more a more grammatical-sounding first sentence?

2019-10-22 13:34 UTC, dz333 commented
I think I've addressed all of your concerns, but github seems to think I haven't haha (it still says change requested).

2019-10-22 14:29 UTC, sampsyo approved these changes
Great! To make that indicator go away, I think you have to "request a review." But no need; I'll merge this now!

2019-10-22 14:29 UTC, merged