Project 2: Lazy code motion
sampsyo/cs6120 pull request #98
Opened 2019-10-29 18:03 UTC by hackedy

2019-11-06 19:49 UTC, sampsyo requested changes
Very nice and clearly explained work! :tada: I have only a handful of low-level comments within.

2019-11-06 19:49 UTC, sampsyo commented on content/blog/2019-10-26-lazy-code-motion/index.md
> +is written in Python, this meant I had to implement Bril JSON parsing and design
Well, it's written in a ridiculous mishmash of Python and TypeScript.

2019-11-06 19:49 UTC, sampsyo commented on content/blog/2019-10-26-lazy-code-motion/index.md
> +detail but could have performance or code size implications.
In an ideal world, there would be an off-the-shelf "CFG simplification" pass that you could run after your pass to clean up these easily-coalescable cases.

2019-11-06 19:49 UTC, sampsyo commented on content/blog/2019-10-26-lazy-code-motion/index.md
> +```
FWIW, I think our Markdown processor supports [tables](https://github.github.com/gfm/#tables-extension-), so you can turn this into a legit table if you want.

2019-11-27 22:18 UTC, hackedy commented
Thanks for the feedback, I tried to address it and fix the table formatting as well.

2019-11-28 13:38 UTC, sampsyo approved these changes
Excellent work.

2019-11-28 13:38 UTC, merged